language: python
dist: trusty
matrix:
  include:
    - python: '2.7'
      env: RUNTESTS="tox -v"
      install: pip install tox
    - python: '3.5'
      env: RUNTESTS="tox -v"
      install: pip install tox
    - env: RUNTESTS="gradle check"
      addons:
        apt:
          packages:
            - gradle
      after_failure:
        - cat build/reports/codenarc/main.txt
script:
  - bash -c "$RUNTESTS"
